### PR TITLE
isa: add addr_mode handler for LD{B}, STR{B}

### PR DESCRIPTION
**Pull request by jailuthra**
@parthmittal @abrolmrinal someone pls review this

### CODE REVIEW

**Comment by parthmittal** [comment]
@jailuthra Possibly is dumb question, but is it legal to assign to a const variable a non const rvalue?

**Comment by jailuthra** [comment]
@parthmittal yes, this just makes sure the value remains unchanged through the lvalue accesses

**Comment by parthmittal** [comment]
@jailuthra My bad, this is good.

**Comment by jailuthra** [comment]
@RadhikaG summoned for review

**Comment by parthmittal** [comment]
@jailuthra I think there is cool assign button, use that and we'll be coolest project ever

**Comment by jailuthra** [comment]
@parthmittal done

**Pull request merged**
